.PHONY: dev test build fmt clippy pre-commit clean

dev:
	./qbak-docker.sh dev

test:
	./qbak-docker.sh test

build:
	./qbak-docker.sh build

fmt:
	./qbak-docker.sh fmt

clippy:
	./qbak-docker.sh clippy

pre-commit:
	./qbak-docker.sh pre-commit

clean:
	./qbak-docker.sh clean
